# 00_TensorFlow Fundamentals Exercises

In [2]:
import tensorflow as tf

##### 1. Create a vector, scalar, matrix and tensor with values of your choosing

In [3]:
vector = tf.constant([1,3,2])
scalar = tf.constant(7)
matrix = tf.constant([[1,3,1,2],[2,4,1,1]])
tensor = tf.constant([[[0,4,7,1],[2,5,8,0]],[[3,6,0,9],[2,0,4,6]]])

scalar,vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 2])>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 3, 1, 2],
        [2, 4, 1, 1]])>,
 <tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
 array([[[0, 4, 7, 1],
         [2, 5, 8, 0]],
 
        [[3, 6, 0, 9],
         [2, 0, 4, 6]]])>)

##### 2. Find the shape, rank and size of the tensors you created in 1.

In [4]:
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.size(tensor)}')
print(f'The rank of the tensor: {tf.rank(tensor)}')

The shape of the tensor: (2, 2, 4)
The rank of the tensor: 16
The rank of the tensor: 3


##### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [5]:
tf.random.set_seed=13

tensor1 = tf.random.uniform(shape=(5,300))
tensor2=tf.random.uniform(shape=(5,300))

tensor1, tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.528823  , 0.27664876, 0.32517636, ..., 0.43363643, 0.5378666 ,
         0.7005279 ],
        [0.1258552 , 0.18286431, 0.26014984, ..., 0.10656118, 0.63404703,
         0.60949004],
        [0.992887  , 0.48227477, 0.5150981 , ..., 0.967713  , 0.49950612,
         0.4830464 ],
        [0.5565345 , 0.0011065 , 0.7171215 , ..., 0.30959845, 0.98127246,
         0.4050467 ],
        [0.35197592, 0.5999595 , 0.49482   , ..., 0.35136604, 0.24200666,
         0.7471186 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.09688103, 0.5591841 , 0.973456  , ..., 0.6585617 , 0.8348553 ,
         0.3433913 ],
        [0.16670692, 0.07889605, 0.26343727, ..., 0.06876683, 0.96000874,
         0.58784854],
        [0.49491525, 0.74842024, 0.9352224 , ..., 0.6135709 , 0.22713745,
         0.90821457],
        [0.79737175, 0.47870624, 0.2576542 , ..., 0.6389637 , 0.69230354,
         0.81039166],
        [0.03430

##### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [7]:
print(tensor1.shape)
print(tensor2.shape)

#have to transpose for matrix multiplication

(5, 300)
(5, 300)


In [11]:
multi_tensor=tf.matmul(tensor1, tf.transpose(tensor2))
multi_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.168945, 76.72226 , 78.953026, 77.369316, 78.256744],
       [67.197296, 73.89367 , 74.25696 , 74.14812 , 75.17505 ],
       [75.043175, 76.59996 , 76.60998 , 80.282845, 73.92431 ],
       [70.02668 , 74.82189 , 73.08032 , 73.120125, 70.63795 ],
       [77.34724 , 77.34846 , 77.34693 , 76.08661 , 75.10142 ]],
      dtype=float32)>

In [9]:
print(multi_tensor.shape)

(5, 5)


##### 5. Multiply the two tensors you created in 3 using dot product.

In [12]:
tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.168945, 76.72226 , 78.953026, 77.369316, 78.256744],
       [67.197296, 73.89367 , 74.25696 , 74.14812 , 75.17505 ],
       [75.043175, 76.59996 , 76.60998 , 80.282845, 73.92431 ],
       [70.02668 , 74.82189 , 73.08032 , 73.120125, 70.63795 ],
       [77.34724 , 77.34846 , 77.34693 , 76.08661 , 75.10142 ]],
      dtype=float32)>

##### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [13]:
new_tensor = tf.random.uniform(shape=[224,224,3], minval=0, maxval=1)
new_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.37416458, 0.6307963 , 0.53541005],
        [0.98208094, 0.73580396, 0.25518465],
        [0.29207778, 0.14127958, 0.857793  ],
        ...,
        [0.7095814 , 0.8013557 , 0.09357834],
        [0.85991514, 0.74908495, 0.3988005 ],
        [0.1941812 , 0.569517  , 0.17335296]],

       [[0.60314345, 0.6027242 , 0.9692625 ],
        [0.859589  , 0.55369973, 0.9981142 ],
        [0.24198568, 0.3361951 , 0.69956505],
        ...,
        [0.7916584 , 0.1495285 , 0.09814727],
        [0.94855607, 0.49786448, 0.8443761 ],
        [0.8216512 , 0.13430262, 0.4001999 ]],

       [[0.8015156 , 0.2896229 , 0.5025139 ],
        [0.76175666, 0.18244743, 0.79041755],
        [0.4322121 , 0.85170746, 0.6054039 ],
        ...,
        [0.6030979 , 0.23060477, 0.45130384],
        [0.42414057, 0.3098489 , 0.3137319 ],
        [0.21056128, 0.9941344 , 0.9767755 ]],

       ...,

       [[0.889282  , 0.9033694 , 0.9165578 ],
        [0.69

##### 7. Find the min and max values of the tensor you created in 6.

In [15]:
print(f'Maximum value: {tf.reduce_max(new_tensor)}')
print(f'Minimum value: {tf.reduce_min(new_tensor)}')

Maximum value: 0.999996542930603
Minimum value: 9.5367431640625e-07


##### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [16]:
random_tensor = tf.random.Generator.from_seed(13)
random_tensor = random_tensor.normal(shape=(1,224,224,3))
random_tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 0.37944323, -0.6664026 ,  0.6054596 ],
         [ 0.19181173,  0.8045827 ,  0.4769051 ],
         [-0.7812124 , -0.996891  ,  0.33149973],
         ...,
         [ 0.9765769 , -1.0644387 , -0.15964095],
         [ 0.20708817, -0.88769746, -0.4291407 ],
         [ 1.0496043 ,  0.85257185,  0.36788857]],

        [[ 0.5011535 , -0.448121  ,  0.3995735 ],
         [-2.1588635 , -0.16122076, -1.040813  ],
         [ 0.44564843, -1.1353635 ,  0.06766166],
         ...,
         [ 0.88542104, -0.5249761 , -0.3797743 ],
         [-0.3626551 , -0.1668443 , -0.01824445],
         [ 1.229008  ,  1.5113504 , -0.57362217]],

        [[ 0.06148814, -0.43045416, -0.04233417],
         [-1.3867607 , -1.276255  ,  0.01142067],
         [ 0.34232524,  1.9177431 ,  1.5253149 ],
         ...,
         [ 1.1458824 , -1.2572527 ,  0.9534838 ],
         [-0.79259014,  0.8151953 , -1.4620315 ],
         [ 0.46462342, -0.9431774 , -0.3278202

In [17]:
print(random_tensor.shape)

(1, 224, 224, 3)


In [18]:
squeezed_tensor = tf.squeeze(random_tensor)
squeezed_tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.37944323, -0.6664026 ,  0.6054596 ],
        [ 0.19181173,  0.8045827 ,  0.4769051 ],
        [-0.7812124 , -0.996891  ,  0.33149973],
        ...,
        [ 0.9765769 , -1.0644387 , -0.15964095],
        [ 0.20708817, -0.88769746, -0.4291407 ],
        [ 1.0496043 ,  0.85257185,  0.36788857]],

       [[ 0.5011535 , -0.448121  ,  0.3995735 ],
        [-2.1588635 , -0.16122076, -1.040813  ],
        [ 0.44564843, -1.1353635 ,  0.06766166],
        ...,
        [ 0.88542104, -0.5249761 , -0.3797743 ],
        [-0.3626551 , -0.1668443 , -0.01824445],
        [ 1.229008  ,  1.5113504 , -0.57362217]],

       [[ 0.06148814, -0.43045416, -0.04233417],
        [-1.3867607 , -1.276255  ,  0.01142067],
        [ 0.34232524,  1.9177431 ,  1.5253149 ],
        ...,
        [ 1.1458824 , -1.2572527 ,  0.9534838 ],
        [-0.79259014,  0.8151953 , -1.4620315 ],
        [ 0.46462342, -0.9431774 , -0.3278202 ]],

       ...,

     

##### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [19]:
my_tensor = tf.constant([8,13,12,24,11,99,0,78,66,45])
my_tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 8, 13, 12, 24, 11, 99,  0, 78, 66, 45])>

In [20]:
max_index = tf.argmax(my_tensor)

In [21]:
print(f'The indices where the value is maximum: {max_index}')
print(f'The maximum value was: {my_tensor[max_index]}')

The indices where the value is maximum: 5
The maximum value was: 99


##### 10. One-hot encode the tensor you created in 9.

In [22]:
tf.one_hot(my_tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>